name: SLSA Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, 386, arm64, arm]
        exclude:
          - goarch: 386
            goos: darwin
          - goarch: arm
            goos: darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Initialize Go Modules
        run: |
          go mod init xuanqiong
          go mod tidy
        
      - name: Build
        run: |
          cd backend
          for GOOS in ${{ matrix.goos }}; do
            for GOARCH in ${{ matrix.goarch }}; do
              echo "Building for $GOOS/$GOARCH"
              GOOS=$GOOS GOARCH=$GOARCH go build -o xuanqiong-$GOOS-$GOARCH main.go
              zip -r xuanqiong-$GOOS-$GOARCH.zip backend/xuanqiong-$GOOS-$GOARCH config.yaml
            done
          done

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: backend/xuanqiong-*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
