name: SLSA Go Releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, 386, arm64, arm]
        exclude:
          - goos: darwin
            goarch: 386

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true

    - name: Build
      run: |
        echo "Building for ${{ matrix.goos }}-${{ matrix.goarch }}"
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=1 go build -v -o ./backend/${{ matrix.goos }}-${{ matrix.goarch }} ./backend/...

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./backend/${{ matrix.goos }}-${{ matrix.goarch }}

  generate_provenance:
    needs: build
    runs-on: ubuntu-latest
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.4.0
    with:
      go-version: '1.20'
      # 注意：这里需要确保前一个作业输出了正确的哈希值，并传递给这个作业
      base64-subjects: ${{ needs.build.outputs.digests }}
      upload-assets: true

  release:
    needs: [build, generate_provenance]
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./bin/

    - name: Upload Release Assets
      uses: shogo82148/actions-upload-release-artifact@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_dir: ./bin/
