name: SLSA Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, 386, arm64, arm]
        exclude:
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: arm
          - goos: windows
            goarch: arm64
          - goos: windows
            goarch: arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build
        run: |
          cd backend
          for GOOS in ${{ matrix.goos }}; do
            for GOARCH in ${{ matrix.goarch }}; do
              echo "Building for $GOOS/$GOARCH"
              GOOS=$GOOS GOARCH=$GOARCH go build -o xuanqiong-$GOOS-$GOARCH main.go
              if [ "$GOOS" = "windows" ]; then
                zip -r xuanqiong-$GOOS-$GOARCH.zip xuanqiong-$GOOS-$GOARCH.exe config.yaml
              else
                zip -r xuanqiong-$GOOS-$GOARCH.zip xuanqiong-$GOOS-$GOARCH config.yaml
              fi
            done
          done

      - name: Parse CHANGELOG
        id: parse_changelog
        run: |
          version=$(grep -E '## \[([0-9]+\.[0-9]+\.[0-9]+)\] - [0-9]{4}-[0-9]{2}-[0-9]{2}.*' CHANGELOG.md | head -n 1 | sed -E 's/## \[([0-9]+\.[0-9]+\.[0-9]+)\] - [0-9]{4}-[0-9]{2}-[0-9]{2}(.*)/\1 \2/')
          description=$(awk '/## \[/ {if (found) {found=0; exit} else {found=1; next}} found' CHANGELOG.md)
          echo "Latest Version: $version"
          echo "Release Notes: $description"
          echo "RELEASE_TAG=$version" >> $GITHUB_OUTPUT
          echo "RELEASE_NOTES=$description" >> $GITHUB_OUTPUT

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: backend/xuanqiong-*.zip
          tag: ${{ steps.parse_changelog.outputs.RELEASE_TAG }}
          body: ${{ steps.parse_changelog.outputs.RELEASE_NOTES }}
          overwrite: true
          file_glob: true
